program HANSYS;

uses
  Vcl.Forms,
  SysUtils,
  UfrmPrincipal in 'UfrmPrincipal.pas' {frmPrincipal},
  UfrmFichadeCadastro in 'UfrmFichadeCadastro.pas' {frmFichadeCadastro},
  UfrmLogin in 'UfrmLogin.pas' {frmLogin},
  UdmPrincipal in 'UdmPrincipal.pas' {dmPrincipal: TDataModule},
  UdmFicha in 'UdmFicha.pas' {dmFicha: TDataModule},
  UfrmFotosdiagnostico in 'UfrmFotosdiagnostico.pas' {frmFotosdiagnostico},
  UFuncoes in 'UFuncoes.pas',
  UfrmMenudeRelatorios in 'UfrmMenudeRelatorios.pas' {frmMenudeRelatorios},
  UfrmCalendario in 'UfrmCalendario.pas' {frmCalendario},
  UfrmResidAnteriores in 'UfrmResidAnteriores.pas' {frmResidAnteriores},
  USobre in 'USobre.pas' {frmSobre},
  UfrmFotosRecidiva in 'UfrmFotosRecidiva.pas' {frmFotosRecidiva},
  UfrmInstrucoes in 'UfrmInstrucoes.pas' {frmInstrucoes},
  UfrmFotoComunicante in 'UfrmFotoComunicante.pas' {frmFotoComunicante},
  UfrmCoresMD1 in 'UfrmCoresMD1.pas' {frmCoresMD1},
  UfrmCoresMD2 in 'UfrmCoresMD2.pas' {frmCoresMD2},
  UfrmCoresMD3 in 'UfrmCoresMD3.pas' {frmCoresMD3},
  UfrmCoresMD4 in 'UfrmCoresMD4.pas' {frmCoresMD4},
  UfrmCoresMD5 in 'UfrmCoresMD5.pas' {frmCoresMD5},
  UfrmCoresMD6 in 'UfrmCoresMD6.pas' {frmCoresMD6},
  UfrmCoresMD7 in 'UfrmCoresMD7.pas' {frmCoresMD7},
  UfrmCoresME1 in 'UfrmCoresME1.pas' {frmCoresME1},
  UfrmCoresME2 in 'UfrmCoresME2.pas' {frmCoresME2},
  UfrmCoresME3 in 'UfrmCoresME3.pas' {frmCoresME3},
  UfrmCoresME4 in 'UfrmCoresME4.pas' {frmCoresME4},
  UfrmCoresME5 in 'UfrmCoresME5.pas' {frmCoresME5},
  UfrmCoresME6 in 'UfrmCoresME6.pas' {frmCoresME6},
  UfrmCoresME7 in 'UfrmCoresME7.pas' {frmCoresME7},
  UfrmCoresPD1 in 'UfrmCoresPD1.pas' {frmCoresPD1},
  UfrmCoresPD2 in 'UfrmCoresPD2.pas' {frmCoresPD2},
  UfrmCoresPD3 in 'UfrmCoresPD3.pas' {frmCoresPD3},
  UfrmCoresPD4 in 'UfrmCoresPD4.pas' {frmCoresPD4},
  UfrmCoresPD5 in 'UfrmCoresPD5.pas' {frmCoresPD5},
  UfrmCoresPD6 in 'UfrmCoresPD6.pas' {frmCoresPD6},
  UfrmCoresPD7 in 'UfrmCoresPD7.pas' {frmCoresPD7},
  UfrmCoresPD8 in 'UfrmCoresPD8.pas' {frmCoresPD8},
  UfrmCoresPD9 in 'UfrmCoresPD9.pas' {frmCoresPD9},
  UfrmCoresPD10 in 'UfrmCoresPD10.pas' {frmCoresPD10},
  UfrmCoresPE1 in 'UfrmCoresPE1.pas' {frmCoresPE1},
  UfrmCoresPE2 in 'UfrmCoresPE2.pas' {frmCoresPE2},
  UfrmCoresPE3 in 'UfrmCoresPE3.pas' {frmCoresPE3},
  UfrmCoresPE4 in 'UfrmCoresPE4.pas' {frmCoresPE4},
  UfrmCoresPE5 in 'UfrmCoresPE5.pas' {frmCoresPE5},
  UfrmCoresPE6 in 'UfrmCoresPE6.pas' {frmCoresPE6},
  UfrmCoresPE7 in 'UfrmCoresPE7.pas' {frmCoresPE7},
  UfrmCoresPE9 in 'UfrmCoresPE9.pas' {frmCoresPE9},
  UfrmCoresPE8 in 'UfrmCoresPE8.pas' {frmCoresPE8},
  UfrmCoresPE10 in 'UfrmCoresPE10.pas' {frmCoresPE10},
  UfrmConfig in 'UfrmConfig.pas' {FrmConfig},
  Vcl.Themes,
  Vcl.Styles,
  UfrmPesqDadosPaciente in 'UfrmPesqDadosPaciente.pas' {frmPesqDadosPaciente},
  UdmFichaEstudante in 'UdmFichaEstudante.pas' {dmFichaEstudante: TDataModule},
  UfrmFichaEstudantes in 'UfrmFichaEstudantes.pas' {frmFichaEstudantes},
  UfrmPesqEstudantes in 'UfrmPesqEstudantes.pas' {frmPesqEstudantes},
  UfrmCadUsuario in 'UfrmCadUsuario.pas' {frmCadUsuario},
  UdmSINAN in 'UdmSINAN.pas' {dmSINAN: TDataModule},
  UfrmPesquisaSINAN in 'UfrmPesquisaSINAN.pas' {frmPesquisaSINAN},
  UdmEstudantecomu in 'UdmEstudantecomu.pas' {dmEstudantecomu: TDataModule},
  UfrmComunicantesEstu in 'UfrmComunicantesEstu.pas' {frmComunicantesEstu},
  UdmRelatEstudantes in 'UdmRelatEstudantes.pas' {dmRelatEstudantes: TDataModule},
  UfrmRelatListEstuCidade in 'UfrmRelatListEstuCidade.pas' {frmRelatListEstuCidade};

{$R *.res}

begin
  Application.Initialize;
  Application.MainFormOnTaskbar := True;
  Application.CreateForm(TfrmPrincipal, frmPrincipal);
  Application.Run;
end.
